# Generated by Django 5.1.4 on 2024-12-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_page_category_tabledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_not_converted',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
