# Generated by Django 5.1.4 on 2024-12-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_vacancy_salary_not_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
