# Generated by Django 5.1.4 on 2024-12-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_vacancy_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_not_converted',
        ),
    ]
