# Generated by Django 5.1.4 on 2024-12-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_vacancy_salary_not_converted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('exchange_rate', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
