# Generated by Django 5.1.4 on 2024-12-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_currencyexchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='currency',
            field=models.CharField(max_length=10),
        ),
    ]
